//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18._02._2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Platform { get; set; }

        public override string ToString()
        {
            return Name;
        }

        private int DeveloperId { get; set; }
        private int Distributor_Id { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Distributor Distributor { get; set; }
    }
}
