//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13._02._2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string NameOfCapital { get; set; }
        public int Population { get; set; }
        public int Area { get; set; }
        public string PartOfWorld { get; set; }
    }
}
